# Generated by Django 2.0.2 on 2018-02-04 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed GameObject', max_length=255)),
                ('tick_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Resource', max_length=255)),
                ('mass', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='SpacecraftPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Spacecraft Part', max_length=255)),
                ('mass', models.FloatField(default=100.0)),
            ],
        ),
        migrations.CreateModel(
            name='SpacecraftResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Resource')),
            ],
        ),
        migrations.CreateModel(
            name='Positionable',
            fields=[
                ('gameobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.GameObject')),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
                ('z', models.FloatField(default=0.0)),
            ],
            bases=('core.gameobject',),
        ),
        migrations.CreateModel(
            name='Movable',
            fields=[
                ('positionable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Positionable')),
                ('vx', models.FloatField(default=0.0)),
                ('vy', models.FloatField(default=0.0)),
                ('vz', models.FloatField(default=0.0)),
            ],
            bases=('core.positionable',),
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('movable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Movable')),
                ('mass', models.FloatField(default=7.34767309e+22)),
            ],
            bases=('core.movable',),
        ),
        migrations.CreateModel(
            name='Spacecraft',
            fields=[
                ('movable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Movable')),
            ],
            bases=('core.movable',),
        ),
        migrations.AddField(
            model_name='spacecraftresource',
            name='spacecraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Spacecraft'),
        ),
        migrations.AddField(
            model_name='spacecraftpart',
            name='spacecraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='core.Spacecraft'),
        ),
        migrations.AddField(
            model_name='spacecraft',
            name='resources',
            field=models.ManyToManyField(through='core.SpacecraftResource', to='core.Resource'),
        ),
    ]
